services:
  seed-add-blocks:
    build:
      context: ../../
      dockerfile: apps/seed-add-blocks/Dockerfile
      additional_contexts:
        hivego: /home/milo/Documents/vsc/hivego
    command: ["-network", "testnet4", "-max_blocks", "128"]
    volumes:
      - ./data/devnet:/app/data
      - ./last_height:/app/last_height
    networks:
      - haf
    restart: unless-stopped

networks:
  haf:
    external: true
