services:
  lite-btc-oracle:
    build:
      context: ../../
      dockerfile: apps/lite-btc-oracle/Dockerfile
    container_name: lite-btc-devnet-oracle
    volumes:
      - ./data/devnet:/app/data
      - ./data/devnet/last-height:/app/last-height
    networks:
      - haf

networks:
  haf:
    external: true
